### ISSUE TITLE
[Why do we use User ID for signin?]

### ISSUE THREAD

**Issue by rvvergara** [mumani/Associations#7]
![image](https://user-images.githubusercontent.com/6015315/58443634-adbb0a00-8125-11e9-9051-66cb40aab414.png)

This is weird. Why didn't we use email or username? Any user will be confused as nobody memorizes his/her user id. 

I know you put in the User show page the user's id but still that's strange. Let's make the signin more convenient for users.

![image](https://user-images.githubusercontent.com/6015315/58443663-f70b5980-8125-11e9-89e5-66a3293a9f44.png)

**Comment by newcoder171** [comment]
![id](https://user-images.githubusercontent.com/33447805/58522550-c58f9e00-81b8-11e9-8037-a9ecbb5e7a89.PNG)

I don't have username for I went for the first option they suggested

**Comment by rvvergara** [comment]
We can choose the name instead of the ID.

Tip: Odin may be giving us the minimum requirements of the project. But we have to think like this is a real world app where we want users to have a good experience when using our app.

**Comment by newcoder171** [comment]
you cannot use name for login

**Comment by rvvergara** [comment]
Issue resolved! Awesome
